version: '3.7'

services:
    backend:
        image: "cr.yandex/crpn29pj78m9nr559c1h/market_backend:0.1"
        environment:
            AWS_ACCESS_KEY_ID: ${MARKET_YC_ID}
            AWS_SECRET_ACCESS_KEY: ${MARKET_YC_KEY}

            MARKET_YC_BUCKET: ${MARKET_YC_BUCKET}

            MARKET_MAIL_ORG: ${MARKET_MAIL_ORG}
            MARKET_MAIL_ORG_PASSWORD: ${MARKET_MAIL_ORG_PASSWORD}
            MARKET_MAIL_SUPPORT: ${MARKET_MAIL_SUPPORT}
            MARKET_MAIL_SUPPORT_PASSWORD: ${MARKET_MAIL_SUPPORT_PASSWORD}
            MARKET_MAIL_SALES: ${MARKET_MAIL_SALES}
            MARKET_MAIL_SALES_PASSWORD: ${MARKET_MAIL_SALES_PASSWORD}

            MARKET_POSTGRES_PASSWORD: ${MARKET_POSTGRES_PASSWORD}
            MARKET_POSTGRES_DB: ${MARKET_POSTGRES_DB}

            MARKET_TELEGRAM_KEY: ${MARKET_TELEGRAM_KEY}
            MARKET_ADDRESS_SUGGEST_KEY: ${MARKET_ADDRESS_SUGGEST_KEY}

            MARKET_SMS_LOGIN: ${MARKET_SMS_LOGIN}
            MARKET_SMS_PASSWORD: ${MARKET_SMS_PASSWORD}
        ports:
            - "6543:6543"
        depends_on:
            - postgresql
            - redis
    frontend:
        image: "cr.yandex/crpn29pj78m9nr559c1h/market_frontend:0.1"
        volumes:
            - ./custom.conf:/etc/nginx/conf.d/default.conf
            - ./dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker-volumes/etc/letsencrypt/live/veggies.market/fullchain.pem:/etc/letsencrypt/live/veggies.market/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/veggies.market/privkey.pem:/etc/letsencrypt/live/veggies.market/privkey.pem
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - backend
    redis:
        image: "redis:5.0.6-alpine"
        ports:
            - "6379:6379"
    postgresql:
        image: "postgres:12.0-alpine"
        environment:
            POSTGRES_PASSWORD: ${MARKET_POSTGRES_PASSWORD}
            POSTGRES_DB: ${MARKET_POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
